version: "3.9"

services:
  api:
    build:
      context: .
      target: development
    env_file: .env
    ports:
      - "8001:8001"
    depends_on:
      - timescaledb
      - redis
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload

  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: analytics_timescaledb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: analytics_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - timescale_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: analytics_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  jupyter:
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
    depends_on:
      - timescaledb
      - redis
    command: start-notebook.sh --NotebookApp.token='' --NotebookApp.password='' --NotebookApp.allow_root=True

volumes:
  timescale_data:
  redis_data: